# _config.yml
# Jekyll configuration file for Valentyn S theme

title: Valentyn S
description: "Extracts Everything"
url: "https://valpere.github.io"
baseurl: ""

# Build settings
markdown: kramdown
highlighter: rouge
theme: null # Disable default theme to use custom files

# Custom theme settings
sass:
  style: compressed
  load_paths:
    - _sass

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Custom variables
colors:
  primary: "#168A53"
  accent: "#FED74F"
  text: "#000000"
  background: "#ffffff"

# Default layout settings
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

# Exclude files
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock