# frozen_string_literal: true

# Multilingual sitemap generator for Jekyll + jekyll-polyglot.
#
# Walks the generated _site/ tree directly (not site.pages) because
# jekyll-polyglot with parallel_localization: false renders UK pages
# to disk but does NOT register them as separate Page objects on
# site.pages — only the *-ua.md source files appear there. Walking
# the rendered output gives a true 1:1 EN↔UK mirror.
#
# Replaces jekyll-sitemap, which jekyll-polyglot forces on even when
# removed from the plugins list. The generated /uk/sitemap.xml from
# jekyll-sitemap is wrong (it contains EN URLs without /uk/ prefix);
# this generator produces a single correct multilingual sitemap at
# /sitemap.xml and deletes the bogus /uk/sitemap.xml.
#
# GH Pages safe: no external gem requires.

require "pathname"

module Jekyll
  class PolyglotSitemap
    EXCLUDE_PATH_RE = %r{
      \A/
      (?: assets/
      | robots\.txt
      | 404\.html
      | sitemap\.xml
      | search\.html
      | feed\.xml
      )
    }x

    # Run after polyglot has finished writing all per-language pages.
    # :post_write fires once per write pass; in polyglot mode there is
    # one pass for default-lang pages, then another for non-default-lang
    # pages. We do the same: walk whichever subset of files exists in
    # _site/ right now and accumulate. The single global pair map ensures
    # hreflang siblings resolve correctly across both passes.
    @state = { pairs: {}, processed: 0 }
    @mutex = Mutex.new

    def self.write(site)
      # polyglot mutates site.dest between passes (to "_site/uk" during the
      # UK pass). Use a stable base derived from site.source + "/_site"
      # instead so we always walk the full output tree.
      base = File.expand_path("_site", site.source)
      site_url = site.config["url"].to_s.sub(%r{/$}, "")

      html_files = Dir.glob(File.join(base, "**", "index.html"))

      html_files.each do |path|
        rel = Pathname.new(path).relative_path_from(Pathname.new(base)).to_s
        url = "/" + File.dirname(rel) + "/"
        url = "/" if url == "//"

        next if url =~ EXCLUDE_PATH_RE

        lang = url.start_with?("/uk/") ? "uk" : "en"
        loc = "#{site_url}#{url}"
        # Canonical key strips the /uk/ prefix so EN and UK pair up.
        canonical = url.start_with?("/uk/") ? url.sub(%r{\A/uk}, "") : url

        @mutex.synchronize do
          @state[:pairs][canonical] ||= {}
          @state[:pairs][canonical][lang] = { loc: loc, lastmod: lastmod_for(path) }
          @state[:processed] += 1
        end
      end

      # Build + write sitemap.xml once, only on the last pass. Detect
      # "last pass" by checking whether any /uk/ file we just saw is
      # newer than our sitemap.xml (heuristic: just always rewrite —
      # the final pass wins because we accumulate into @state).
      xml = build_xml(@state[:pairs], site_url)
      File.write(File.join(base, "sitemap.xml"), xml)

      # Delete bogus /uk/sitemap.xml generated by jekyll-sitemap (it
      # contains EN URLs without /uk/ prefix — a known polyglot bug).
      uk_sitemap = File.join(base, "uk", "sitemap.xml")
      File.delete(uk_sitemap) if File.exist?(uk_sitemap)

      Jekyll.logger.info "PolyglotSitemap:",
                         "wrote sitemap.xml — #{@state[:processed]} index.html files indexed"
    end

    def self.lastmod_for(path)
      mtime = File.mtime(path)
      mtime.utc.strftime("%Y-%m-%dT%H:%M:%S+00:00")
    rescue StandardError
      nil
    end

    def self.build_xml(pairs, site_url)
      xml = +""
      xml << %(<?xml version="1.0" encoding="UTF-8"?>\n)
      xml << %(<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"\n)
      xml << %(        xmlns:xhtml="http://www.w3.org/1999/xhtml">\n)

      pairs.each do |_canonical, langs|
        langs.each do |lang, info|
          xml << "  <url>\n"
          xml << "    <loc>#{info[:loc]}</loc>\n"
          xml << "    <lastmod>#{info[:lastmod]}</lastmod>\n" if info[:lastmod]
          # self-reference
          xml << %(    <xhtml:link rel="alternate" hreflang="#{lang}" href="#{info[:loc]}"/>\n)
          # sibling
          if langs.size == 2
            other_lang = lang == "en" ? "uk" : "en"
            other = langs[other_lang]
            xml << %(    <xhtml:link rel="alternate" hreflang="#{other_lang}" href="#{other[:loc]}"/>\n)
            # x-default always points to EN
            en = langs["en"] || info
            xml << %(    <xhtml:link rel="alternate" hreflang="x-default" href="#{en[:loc]}"/>\n)
          end
          xml << "  </url>\n"
        end
      end

      xml << "</urlset>\n"
      xml
    end
  end
end

Jekyll::Hooks.register :site, :post_write do |site|
  Jekyll::PolyglotSitemap.write(site)
end

# Final cleanup: delete the duplicate /uk/sitemap.xml. polyglot re-runs
# the whole site process for non-default languages and writes a second
# sitemap at /uk/sitemap.xml; we don't need it (Google only needs one
# canonical sitemap with hreflang siblings).
Jekyll::Hooks.register :polyglot, :post_write do |site|
  base = File.expand_path("_site", site.source)
  en_sitemap = File.join(base, "sitemap.xml")
  uk_sitemap = File.join(base, "uk", "sitemap.xml")
  if File.exist?(uk_sitemap)
    File.delete(uk_sitemap)
    Jekyll.logger.info "PolyglotSitemap:", "deleted duplicate /uk/sitemap.xml"
  end
end
